ARDUINO_DIR = /home/berocs/.arduino15
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
#ARDUINO_PLATFORM_LIB_PATH = /home/berocs/sketchbook/
#ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/avr/cores/arduino
#BOARDS_TXT = /usr/share/arduino/hardware/arduino/avr/boards.txt
#ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/avr/variants
#BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/avr/bootloaders
ARDUINO_CORE_PATH = /home/berocs/.arduino15/packages/arduino/hardware/avr/1.6.14/cores/arduino
BOARDS_TXT = /home/berocs/.arduino15/packages/arduino/hardware/avr/1.6.14/boards.txt
ARDUINO_VAR_PATH = /home/berocs/.arduino15/packages/arduino/hardware/avr/1.6.14/variants
BOOTLOADER_PARENT = /home/berocs/.arduino15/packages/arduino/hardware/avr/1.6.14/bootloaders

BOARD_TAG    = diecimila
BOARD_SUB    = atmega328
ARDUINO_LIBS = 

#USER_LIB_PATH  -I= ../lib/avr-printf:../lib/avr-pn532:../lib/avr-usart:../lib/avr-i2c:../lib/avr-sha1:../lib
#OTHER_LIBS = -I../lib/avr-printf -I../lib/avr-pn532 -I../lib/avr-usart -I../lib/avr-i2c -I../lib/avr-sha1 -I../lib
USER_LIB_PATH := $(realpath ../lib)

include /usr/share/arduino/Arduino.mk
